name: datride_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1

  dio: ^5.8.0+1
  web_socket_channel: ^3.0.2
  google_maps_flutter: ^2.11.0
  google_places_flutter: ^2.1.0
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0
  permission_handler: ^11.4.0
  google_maps_webservice2: ^1.0.5
  flutter_google_maps_webservices: ^1.1.1

  socket_io_client: ^3.0.2
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  # json_serializable: ^6.9.4
  # flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.18.1
  debounce_throttle: ^2.0.0
  uuid: ^4.5.1
  flutter_slidable: ^4.0.0
  form_field_validator: ^1.1.0
  rxdart: ^0.27.2
  pull_to_refresh: ^2.0.0
  firebase_core: ^2.6.0
  sign_button: ^2.0.6
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  pin_code_fields: ^8.0.1
  form_validator: ^2.1.1
  fl_chart: ^0.69.0  # Downgraded 
  percent_indicator: ^4.2.4
  google_fonts: ^6.2.1
  camera: ^0.11.1
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.5
  fluttertoast: ^8.2.12
  sliding_up_panel: ^2.0.0+1
  image_picker: ^1.1.2
  flutter_animation_progress_bar: ^2.3.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, uncomment and list them below:
  assets:
    - assets/images/
    - assets/images/transport/
    - assets/icons/

  # To add custom fonts to your application, uncomment and configure below:
  # fonts:
  #   - family: ExampleFont
  #     fonts:
  #       - asset: fonts/ExampleFont-Regular.ttf
  #       - asset: fonts/ExampleFont-Bold.ttf
  #         weight: 700
